use_frameworks!
platform :ios, '10.0'

target 'ThryvUXComponents_Example' do
  pod 'ThryvUXComponents', :path => '../'

  target 'ThryvUXComponents_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.3.0'
  end
end
